on:
  push:
    branches:
      - main

name: test upload
jobs:
  test:
    name: Run CD
    runs-on: ubuntu-latest
    environment: test-env
    steps:
      - uses: effektsvk/github-workflows/.github/workflows/_continuous-delivery.yml@main
        with:
          trunk_branch_name: main
