on:
  workflow_dispatch:

name: test upload
jobs:
  test:
    name: Run CD
    uses: effektsvk/github-workflows/.github/workflows/_continuous-delivery.yml@main
    with:
      trunk_branch_name: main
