on:
  workflow_dispatch:

name: test upload
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Run CD
      uses: effektsvk/github-workflows/.github/workflows/_continuous-delivery.yml@main
